# Generated by Django 5.0.3 on 2024-03-30 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('ubicacion', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.IntegerField()),
                ('barrio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.barrio')),
            ],
        ),
    ]
