# Generated by Django 5.0.3 on 2024-03-30 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='valor',
            new_name='cantidad',
        ),
    ]
