# Generated by Django 5.0.3 on 2024-04-04 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_venta_mes'),
    ]

    operations = [
        migrations.AddField(
            model_name='barrio',
            name='localidad',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
