# Generated by Django 4.2.7 on 2023-11-14 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conexiondb',
            old_name='nome_db',
            new_name='name_db',
        ),
    ]
